vanjaro upgraded to angular 1.8.2
vanjarosoftware/Vanjaro.Platform pull request #1024
Opened 2021-04-06 15:39 UTC by narensingh008

2021-04-06 22:10 UTC, meetmandeep requested changes

2021-04-06 22:10 UTC, meetmandeep commented on DesktopModules/Vanjaro/UXManager/Library/Resources/node_modules/.bin/webpack.config.js
> +    mode: 'development',
Revert this back to production

2021-04-07 04:06 UTC, meetmandeep approved these changes

2021-04-07 04:46 UTC, mksmanish79 approved these changes

2021-04-07 04:47 UTC, merged