181 Add new page from the shortcut menu gives error on the console
vanjarosoftware/Vanjaro.Platform pull request #183
Opened 2020-10-07 13:54 UTC by pankajmandeeps

Close #181

2020-10-08 18:04 UTC, meetmandeep requested changes

2020-10-08 18:04 UTC, meetmandeep commented on DesktopModules/Vanjaro/UXManager/Extensions/Menu/Pages/Views/Setting/Detail.js
> +                            if (Menuextension != undefined && Menuextension.scope() != undefined && Menuextension.scope().$apply != undefined && Menuextension.scope().init != undefined && Menuextensi
This doesn't make sense. There has to be a better way to check for undefined; perhaps use the Menuextension.scope().ui.data.PagesTree in a try catch or utility function? See: https://stackoverflow.com/questions/23808928/javascript-elegant-way-to-check-nested-object-properties-for-null-undefined

@Gaganbird Please assist.

2020-10-09 13:12 UTC, hshimanshusharma reviewed
@pankajmandeeps improve the code, see the comment of @meetmandeep

2020-10-12 10:44 UTC, hshimanshusharma approved these changes

2020-10-13 04:30 UTC, hshimanshusharma approved these changes

2020-10-13 04:31 UTC, hshimanshusharma approved these changes

2020-10-13 04:31 UTC, hshimanshusharma approved these changes

2020-10-13 05:31 UTC, meetmandeep requested changes
See @Gaganbird for changes.

2020-10-21 18:20 UTC, meetmandeep approved these changes

2020-10-21 18:20 UTC, merged