Ref #281 fixed unable  to get workflow logs and states for review
vanjarosoftware/Vanjaro.Platform pull request #282
Opened 2020-10-30 10:47 UTC by narensingh008

Closes #281

2020-10-30 19:52 UTC, meetmandeep requested changes

2020-10-30 19:52 UTC, meetmandeep commented on DesktopModules/Vanjaro/Core/Extensions/Workflow/Review/Managers/ModeratorManager.cs
> +                IReviewComment ReviewContent = Activator.CreateInstance(t) as IReviewComment;
This code does not belong in an extension. The code to load assemblies should be part of WorkflowManager and it needs to be cached.

2020-10-30 19:52 UTC, meetmandeep commented on DesktopModules/Vanjaro/Core/Library/App.config
> +   <add name="SiteSql" connectionString="Data Source=DESKTOP-9SGJF9E\SA;Initial Catalog=dev_vanjaro_local;User ID=sa;Password=20hybridSQL10" providerName="System.Data.SqlClient"/>
This should never be committed. Even though this is local and poses no security risk, we should not commit them with actual values. Let's fix this.

2020-10-30 19:52 UTC, meetmandeep commented on DesktopModules/Vanjaro/Core/Library/Components/Enum.cs
> +            VJPage
Enums must be defined with an integer. Rename to just Page.

2020-10-30 19:52 UTC, meetmandeep commented on DesktopModules/Vanjaro/Core/Library/Factories/NotificationTaskFactory.cs
> +                    string[] binAssemblies = Directory.GetFiles(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "bin")).Where(c => c.EndsWith(".dll") && (c.Contains("Vanjaro.UXManager.Extensions"
This doesn't make sense. Why hardcode Vanjaro Extensions or LiveBlog. This needs to be fixed.

2020-10-30 19:52 UTC, meetmandeep commented on DesktopModules/Vanjaro/Core/Library/Factories/PageFactory.cs
> +                if (Entity == WorkflowLogType.VJPage.ToString())
Consider changing WorkflowLogType to just Worfklow. So ultimately it would look like WorkflowType.Page

2020-10-30 19:52 UTC, meetmandeep commented on DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/PageSetting/PageSetting.cs
> +                        { MenuAction.onClick, "parent.OpenPopUp(event,\"900\",\"right\",\"\", \"" + Editor.Options.SettingsUrl + "\")" }
@Gaganbird Why do we use hardcoded pixel values. Couldn't we support a percentage method?

2020-11-02 10:49 UTC, mksmanish79 approved these changes

2020-11-02 10:59 UTC, nikhilmandeeps approved these changes

2020-11-03 03:59 UTC, Gaganbird approved these changes

2020-11-03 07:53 UTC, hshimanshusharma approved these changes

2020-11-03 19:08 UTC, meetmandeep approved these changes

2020-11-03 19:09 UTC, merged