fixed uxmanager not open for third party apps #360
vanjarosoftware/Vanjaro.Platform pull request #361
Opened 2020-12-01 12:00 UTC by narensingh008

2020-12-01 12:22 UTC, Gaganbird approved these changes

2020-12-01 19:15 UTC, meetmandeep requested changes
@gagan348 @narensingh008 Let's discuss these.

2020-12-22 04:16 UTC, Gaganbird approved these changes

2020-12-22 04:28 UTC, meetmandeep approved these changes

2020-12-22 04:28 UTC, merged