#373 must turn membership provider config.requires unique email to true (in web.config) if use email as username is configured. also validate that all emails are unique
vanjarosoftware/Vanjaro.Platform pull request #386
Opened 2020-12-08 11:14 UTC by hshimanshusharma

Close #373

2020-12-08 17:49 UTC, meetmandeep requested changes

2020-12-08 17:49 UTC, meetmandeep commented on DesktopModules/Vanjaro/Core/Library/Managers/SettingManager.cs
> +                foreach (PortalInfo pinfo in PortalController.Instance.GetPortals())
web.config is a Host Level Setting; why are we doing a loop for each portal?

2020-12-09 06:26 UTC, hshimanshusharma commented on DesktopModules/Vanjaro/Core/Library/Managers/SettingManager.cs
> +                foreach (PortalInfo pinfo in PortalController.Instance.GetPortals())
Loop will work only for the first portal and I shouldn't hardcode portal with 0
PortalId required to check its IsDistribution(pinfo.PortalID)

2020-12-09 06:47 UTC, meetmandeep approved these changes

2020-12-09 06:47 UTC, merged