Scheduler error fixed which occurs when you uninstall the Vanjaro
vanjarosoftware/Vanjaro.Platform pull request #627
Opened 2021-01-28 06:14 UTC by ashishpachauriap

#620 close

2021-01-28 06:36 UTC, mksmanish79 approved these changes

2021-01-28 19:14 UTC, meetmandeep requested changes

2021-01-28 19:14 UTC, meetmandeep commented on DesktopModules/Vanjaro/Core/Library/Install/Uninstall.Migrate.SqlDataProvider
> +delete from {databaseOwner}[{objectQualifier}PersonaBarMenu] where Identifier='Vanjaro'
Why is the file named Uninstall.Migrate.SqlDataProvider? What does Core has to do with Migrate?

2021-01-28 19:14 UTC, meetmandeep commented on DesktopModules/Vanjaro/Core/Library/Install/Uninstall.Migrate.SqlDataProvider
> +GO
Why do we have this same uninstall in two places? Once here and once in Migrate?

2021-01-29 04:50 UTC, meetmandeep approved these changes

2021-01-29 04:50 UTC, merged